name: github-runner

services:
  runner:
    image: myoung34/github-runner:latest
    container_name: github-runner-mundial2026
    restart: unless-stopped
    env_file: ../../../platform/env/github-runner.env.example
    environment:
      REPO_URL: https://github.com/${GITHUB_OWNER}/${GITHUB_REPOSITORY}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_WORKDIR: /tmp/runner/work
      LABELS: ${RUNNER_LABELS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/share/CACHEDEV1_DATA/docker/infra
    networks: [infra]

networks:
  infra:
    external: true
