#!/bin/sh

if [ -z "${DOCKSIDE_ROOT:-}" ]; then
    printf '%s\n' "ERROR: DOCKSIDE_ROOT is not set" >&2
    exit 1
fi

DOCKSIDE_CONFIG_DIR="$DOCKSIDE_ROOT/config"
DOCKSIDE_TEMPLATE_DIR="$DOCKSIDE_ROOT/templates"
DOCKSIDE_ADAPTERS_DIR="$DOCKSIDE_ROOT/adapters"
DOCKSIDE_DOCS_DIR="$DOCKSIDE_ROOT/docs"

export DOCKSIDE_CONFIG_DIR
export DOCKSIDE_TEMPLATE_DIR
export DOCKSIDE_ADAPTERS_DIR
export DOCKSIDE_DOCS_DIR
