#!/bin/sh
. "$DOCKSIDE_HOME/scripts/lib/common.sh"

DOCKSIDE_INSTALL_DIR="${DOCKSIDE_INSTALL_DIR:-/share/CACHEDEV1_DATA/docker/dockside}"
DOCKSIDE_CONFIG_FILE="$DOCKSIDE_INSTALL_DIR/dockside.env"

config_init() {
  mkdir -p "$DOCKSIDE_INSTALL_DIR" "$DOCKSIDE_INSTALL_DIR/logs" "$DOCKSIDE_INSTALL_DIR/backups"

  if [ ! -f "$DOCKSIDE_CONFIG_FILE" ]; then
    cat > "$DOCKSIDE_CONFIG_FILE" <<'EOT'
DOCKER_ROOT=/share/CACHEDEV1_DATA/docker
STACKS_DIR=${DOCKER_ROOT}/stacks
ENV_DIR=${DOCKER_ROOT}/env
BACKUPS_DIR=${DOCKER_ROOT}/backups

TRAEFIK_STACK=traefik
SUPABASE_STACK=supabase
RUNNER_STACK=github-runner

WAIT_TIMEOUT=180
WAIT_INTERVAL=5

TRAEFIK_HEALTH_URL=
SUPABASE_HEALTH_URL=http://127.0.0.1:8000/auth/v1/health
RUNNER_HEALTH_URL=
EOT
  fi
}

config_load() {
  require_file "$DOCKSIDE_CONFIG_FILE"
  . "$DOCKSIDE_CONFIG_FILE"

  WAIT_TIMEOUT="${WAIT_TIMEOUT:-180}"
  WAIT_INTERVAL="${WAIT_INTERVAL:-5}"

  require_dir "$DOCKER_ROOT"
  require_dir "$STACKS_DIR"
  require_dir "$ENV_DIR"
}
